spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 4m4c4llqc102rar85an7icf21q
            client-secret: smlevrksdsv9e1r7se7dd5ikcalbad5k46fmmln5ut35lar9qsk
            clientName: search
            scope: openid
            redirectUriTemplate: https://landonline-search-auth.auth.ap-southeast-2.amazoncognito.com/login/oauth2/code/cognito

        provider:
          cognito:
            issuerUri:https://landonline-search-auth.auth.ap-southeast-2.amazoncognito.com/ap-southeast-2_T50U0r7A4

            usernameAttribute: cognito:username